### PR TITLE
feat: allow CloudEvent to return Response object

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by grayside** [comment]
Per discussion, what we're looking for:

If an exception is thrown, log it and return a 500 status code. Do not return a response body.

**Comment by bshaffer** [comment]
Can we have this show up in Cloud Error Reporting as well? And can we attach a stack trace?

**Comment by grayside** [comment]
I filed https://github.com/GoogleCloudPlatform/functions-framework-php/issues/60 to provide more definition for the needed change. This PR is currently on the wrong track.

**Review by grayside — CHANGES_REQUESTED** [review]
That last comment, but as a request changes flag on the PR :)

**Review by grant — APPROVED** [review]
Edit: Recalled approve, I think we need to specify this more in the contract.

**Comment by grant** [comment]
Right now the contract is a bit arbitrary:

I think we should add a comment/suggestion in the contract and make this more clear in the contract first/at the same time as this PR:

https://github.com/GoogleCloudPlatform/functions-framework/issues/30

**Pull request closed without merging**
