### PR TITLE
Adds <?php to Quickstart

### PR DESCRIPTION
**Pull request by grant**
Fixes part of https://github.com/GoogleCloudPlatform/functions-framework-php/issues/8.

### CODE REVIEW

**Comment by bshaffer** [comment]
Convention in the PHP community is to exclude `<?php` from code snippets in documentation.

**Comment by grant** [comment]
Hey @bshaffer, it's ok to close a PR, but it's not really nice to delete the branch I created.
This quickstart strictly does not work following the instructions verbatim. Won't developers following these instructions run into the same issue I ran into?

**Comment by bshaffer** [comment]
Hey grant! I think you make a good point, since some of these samples are explicitly about copying and pasting the code... I've made a PR here to address this: https://github.com/GoogleCloudPlatform/functions-framework-php/pull/12

As for deleting your branch, I did not mean to offend!

**Comment by grant** [comment]
Cool, thanks for the new PR 😄

**Pull request closed without merging**
