### PR TITLE
feat: uses guzzle/psr and psr-7 instead of http-foundation

### PR DESCRIPTION
**Pull request by bshaffer**
Addresses #23

### CODE REVIEW

**Comment by bshaffer** [comment]
@grant I'll add tests for `Emitter` before I merge. The `headers` function isn't really custom, it should be implementing the bare minimum for the HTTP spec... although it's a little more complex than I'd like.

**Comment by grant** [comment]
> implementing the bare minimum for the HTTP spec 
Yes, it looks like that.

I would assume there'd be a standard library or something for the raw HTTP spec that we could reuse. Maybe there isn't one.

Anyways, looks good to me.

**Comment by grayside** [comment]
Agree with Grant that a library to handle the emitter functionality would be good, but it's just simple enough that avoiding the dependency probably outweighs it. Seems like something which could be changed without a b/c break later.

**Comment by bshaffer** [comment]
@grayside yes, that was my reasoning. There are libraries which handle this, but I don't feel comfortable integrating them into our product. Even relying on `guzzlehttp/psr7` is not optimal.

**Pull request merged**
